name: First CI Workflows
on:
    push:
        branches: [main, dev, New_Feature]
    pull_request:
        branches: [main, dev, New_Feature]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
